### ISSUE TITLE
Adding non ISO 4217 currency

### ISSUE THREAD

**Issue by blackdrag** [JavaMoney/jsr354-ri#182]
I am currently trying to create an instance of MonetaryAmount using:

        MonetaryAmount ma = Monetary.getDefaultAmountFactory()
            .setNumber(new BigDecimal(1))
            .setCurrency("CNH")
            .create();

this fails obviously, because CNH is no ISO 4217 code. Since I do not need converters or anything besides the pure MonetrayAmount object, is there a way to bypass this verification? If not, how could I add this as available currency for MonetaryAmount?

Right now this seems to work:

       MonetaryAmount cny = Monetary.getDefaultAmountFactory()
            .setNumber(new BigDecimal(1))
            .setCurrency("CNY")
            .create();
        CurrencyUnit cu = CurrencyUnitBuilder.of("CNH", cny.getCurrency().getContext()).build(true);

But it feels like I am not using the API correctly.

**Comment by keilw** [comment]
Hi, that is quite likely. See the JavaMoney Bitcoin support https://github.com/JavaMoney/javamoney-shelter/tree/master/digital-currency where a CurrencyUnit is constructed for the non ISO currency Bitcoin.
Hope it helps, if you are happy with the solution, please close the ticket otherwise let us know if you need further help.
