### ISSUE TITLE
How do I provide a custom SPI using Spring injection

### ISSUE THREAD

**Issue by gsbtech** [JavaMoney/jsr354-ri#198]
I could not find a Users Group for this. So, I am posting this question here.
If not appropriate, please indicate where I can post it.

I have created a custom CurrencyProviderSpi that I want to upload in my application without having to modify the *.properties file under META-INF in the release .jar

I tried injecting is as:

@Configuration
public class MyCurrencyConfiguration {

    @Bean
    public CurrencyProviderSpi currencyProviderSpi() {
        return new MyCurrencyUnitSpi();
    }
}

but it did not get loaded by the Bootstrap.

Do you have an example of how I can do it?
I am using Spring Boot 1.5.x, Spring Framework 4.

**Comment by keilw** [comment]
It does not seem the right place here, as Moneta internally does not use Spring Injection. 
The mentioned example also does not look like it would work because if you properly defined `MyCurrencyUnitSpi` to implement the SPI and also put it under `META-INF/services`, that already is Dependency Injection of its own kind and you do not need Spring for that. 
Properly applied through the Service Loader mechanism, you'll get your provider from the JavaMoney.

I'll close this ticket and opened a stub in https://github.com/JavaMoney/javamoney-examples/issues/34. The examples already contain CDI use cases, so in a similar way we could also offer something for Spring Boot. You're welcome to contribute there.
