### ISSUE TITLE
Indian number formatting broken

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-ri#275]
Indian digit grouping is more complex than others

> groups the rightmost three digits together (till the hundreds place) and thereafter groups by sets of two digits

This means that what in the US would be formatted as `67,890,000,000,000` will be formatted in India as `6,78,90,00,00,00,000`.

Consider the following, failing, test:

```java
    /**
     * Test related to parsing and formatting for India.
     */
    @Test
    public void testRupeeFormatting() {
        BigDecimal amount = new BigDecimal("67890000000000");
        Locale india = new Locale("en, IN");

        MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(india);
        Money money = Money.of(amount, "INR");
        String expectedFormattedString = "INR 6,78,90,00,00,00,000.00";
        assertEquals(format.format(money), expectedFormattedString);
        assertEquals(money, Money.parse(expectedFormattedString, format));
    }
```

https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping
https://en.wikipedia.org/wiki/Indian_numbering_system
https://stackoverflow.com/questions/5379231/displaying-currency-in-indian-numbering-format

**Comment by stokito** [comment]
As I remember for China is the same

**Comment by keilw** [comment]
This was among the original goals of JSR 354. It should have worked at some point, so this is also a blocker before getting the MR out. Added the Unit Test method `testRupeeFormatting` to MonetaryFormatsTest, currently disabled.

**Comment by keilw** [comment]
Any idea when the rest could be fixed?

**Comment by stokito** [comment]
Well, since internally is used regular JDK's DecimalFormat so the solution should be similar.
So I searched https://www.google.com.ua/search?q=java+DecimalFormat+inidan+numbers+10000
and the first SO link:
https://stackoverflow.com/questions/25078259/formatting-numbers-in-java-indian-numbering-system
said that this doesn't supported on JDK level.
We should recheck this - maybe it was fixed latter

**Comment by keilw** [comment]
This looks like the Original https://stackoverflow.com/questions/5379231/displaying-currency-in-indian-numbering-format

ICU4J already has support based on its own fork of java.text.Format. Since it is rather large (10MB or more) I don't think we should simply use it in Moneta, but try to use those tickets or ICU itself as inspirations for this.

**Comment by marschall** [comment]
This seems to be the bug in the JDK https://bugs.openjdk.java.net/browse/JDK-4738167

**Comment by keilw** [comment]
Do you think they're gonna fix it before the bug turns 20? ;-(

**Comment by marschall** [comment]
Hope springs eternal

**Comment by stokito** [comment]
Not sure why this is critical for JavaMoney. Yes, we can parse those numbers but if such formatting wasn't supported in JDK then probably it's not so important and we can wait for fix from JDK guys. Can any Indian say how much is this important?

**Comment by keilw** [comment]
It makes the whole thing inconsistent, if parsing works, but formatting doesn't. Given the JDK has ignored it for nearly 20 years now, we may of course still defer it to a new JSR. @atsticks, @otaviojava  WDYT?

**Comment by keilw** [comment]
So is there a workaround or is it too little used to address it?
@atsticks at al, thanks for going over all those, so we can progress with the MR1 as soon as the JCP got back from their OC1 mode.

**Comment by keilw** [comment]
So I guess we can also close https://github.com/JavaMoney/jsr354-ri-bp/issues/55
