### ISSUE TITLE
RoundedMoney. Document deprecated constructors and factory methods

### ISSUE THREAD

**Issue by artbasov** [JavaMoney/jsr354-ri#305]
As per `@Deprecated` documentation:
>@apiNote
It is strongly recommended that the reason for deprecating a program element
be explained in the documentation, using the @deprecated
 javadoc tag. The documentation should also suggest and link to a
recommended replacement API, if applicable. A replacement API often
has subtly different semantics, so such issues should be discussed as
well.
...
The @Deprecated annotation should always be present if the @deprecated javadoc tag is present, and vice-versa.

It would be nice to understand the reasoning behind such deprecation and other options to use instead

**Comment by stokito** [comment]
Yes, we do have some deprecated methods without note about what should be used instead.
for example `RoundingMoney.of()`

**Comment by artbasov** [comment]
In order to form a scope, here is a list of members:

- ` org.javamoney.moneta.RoundedMoney#RoundedMoney(java.lang.Number, javax.money.CurrencyUnit, java.math.MathContext)`

- `org.javamoney.moneta.RoundedMoney#RoundedMoney(java.lang.Number, javax.money.CurrencyUnit, javax.money.MonetaryContext, javax.money.MonetaryOperator)`

- `org.javamoney.moneta.RoundedMoney#of(java.lang.Number, javax.money.CurrencyUnit)`

- `org.javamoney.moneta.RoundedMoney#of(javax.money.CurrencyUnit, java.lang.Number, javax.money.MonetaryContext, javax.money.MonetaryOperator)`

- `org.javamoney.moneta.RoundedMoney#of(java.lang.Number, java.lang.String)`

- `org.javamoney.moneta.RoundedMoney#of(java.lang.Number, java.lang.String, javax.money.MonetaryContext)`

- `org.javamoney.moneta.RoundedMoney#asType(java.lang.Class<T>)`

- `org.javamoney.moneta.RoundedMoney#asType(java.lang.Class<T>, javax.money.MonetaryOperator)`

**Comment by stokito** [comment]
@otaviojava it looks like it's you deprecated most of the methods, could you elaborate on this?

**Comment by keilw** [comment]
I have no real clue, why @otaviojava deprecated them, the version history does not show so clearly why or when he did, because the class got refactored into a modular design of Monata.
The constructors are not used by any external code, so I kept them deprecated and they shall be removed in a future release to use just `of()` methods. Those deprecations make no sense because the `BigDecimal` versions are pure convenience methods, they IMO could be removed, but certainly not those with Number because you should be able to pass a `Double` if the value is not too big as well.
