### ISSUE TITLE
FastMoney: Internal value should be accessible for (de-)serialization purposes

### ISSUE THREAD

**Issue by twwwt** [JavaMoney/jsr354-ri#323]
While `FastMoney.currency` is directly accessibly by means of the getter `getCurrency()`, `FastMoney.number` is not (i.e., there is no public getter or any other way to get its value). This induces an unnecessarily large overhead if one wants to represent a FastMoney instance in a database, or a file, or when serializing it **directly** using the long value of the `number` field (and the `currency` code).

Please add a public getter to `FastMoney`
```java
public long getNumer() {
   return number;
}
```

This would allow for fast serialization of FastMoney instances.

Note that for the other direction, creating a FastMoney instance from a serialized representation (that would have been obtained using this new getter), there is already a possibility:

```java
FastMoney source = // created somehow
CurrencyUnit cu = source.getCurrency();
long number = source.getNumber();

FastMoney target = FastMoney.ofMinor(cu, number, FastMoney.MIN_VALUE.scale());
source.equals(target) // should be true
```

Also, note that the current implementation of `FastMoney.ofMinor(CurrencyUnit, long, int)` can be optimized in case `fractionDigits` equals `SCALE` (5):

```java
public static FastMoney ofMinor(CurrencyUnit currency, long unscaledAmount, int scale) {
   if(scale < 0) {
      throw new IllegalArgumentException("The scale cannot be negative");
   } else if (scale == SCALE) {
      return new FastMoney(unscaledAmount, currency);
   }
   return of(BigDecimal.valueOf(unscaledAmount, scale), currency);
}
```

Edit: The naming of `ofMinor`'s arguments should also be changed to be closer to BigDecimal, which makes their semantics clearer IMHO: ~~amountMinor~~ --> unscaledAmount; ~~fractionDigits~~ --> scale.

I can create a pull request including all the changes proposed by this issue. What do you think?

**Comment by atsticks** [comment]
I dont like the idea of externalizing any internals such as the number, because
1) You can access the number by _numberValue_.
2) It could be that in the future we decide to add the capability of having different number of decimal places in the long, so the long number may vary in semantics inpredictably.
3) As said the number is an implementation detail that should not be exposed. It extends the API with little advantages IMO.

Optimizing ofMinor et al may be an option. But before doing so I would measure the amount of time really being improved with the change. Then we can decide if such a change is worthwhile.
