### ISSUE TITLE
org.javamoney.moneta.Money does not consider itself equal to instances of a different implementation of MonetaryAmount

### ISSUE THREAD

**Issue by michaelbannister** [JavaMoney/jsr354-ri#328]
I would expect that checking equality of two `MonetaryAmount` instances would not be affected by the underlying implementation class.
However, `org.javamoney.moneta.Money` only considers itself equal to instances of the same class.

This is an example using an alternative implementation `io.sphere.sdk.utils.MoneyImpl` provided by `com.commercetools.sdk.jvm.core:commercetools-sdk-base:1.50.0`

```java
package bugs

import io.sphere.sdk.utils.MoneyImpl
import org.javamoney.moneta.Money
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import javax.money.Monetary
import javax.money.MonetaryAmount

class MoneyEqualityTest {

    @Test
    fun `test equality of Money implementations`() {
        val monetaMonetaryAmount = Money.of(50, Monetary.getCurrency("GBP")) as MonetaryAmount
        val sphereMonetaryAmount = MoneyImpl.of(50, Monetary.getCurrency("GBP"))

        assertEquals(sphereMonetaryAmount, monetaMonetaryAmount, "io.sphere.sdk.utils.MoneyImpl's equals method should respect the MonetaryAmount interface") // passes
        assertEquals(monetaMonetaryAmount, sphereMonetaryAmount, "org.javamoney.moneta.Money's equals method should respect the MonetaryAmount interface") // fails
    }
}
```

**Comment by keilw** [comment]
Hi Michael, thanks a lot for the suggestion.
We had a very similar problem in JSR 363/385 which was solved via an `isEquivalentTo()` method, see e.g.: https://github.com/unitsofmeasurement/indriya/issues/268 because strict equality in Java always takes the type into consideration, look at `BigDecimal` vs. `BigInteger` vs. `Integer`, all of them instantiated with 0 or 1 won't be equal to each other. We do not want to break that, so a new major version of the Money JSR or Moneta (385 so far did it on the RI level) will contain that, but for the MR 1 this is a too significant change to include it. We hope to propose a new JSR after that, but let's also see how the whole Corona crisis unfolds and what's going to happen with the JCP in the next few months. If you already joined the JCP as an Associate member you'd be more than welcome to join our efforts towards a new Money JSR. Regards, Werner

**Comment by michaelbannister** [comment]
Ah, thanks – I will suggest that the library I was using which led me to this issue changes to use `isEqualTo`.

I've now found the [javadoc](https://javamoney.github.io/apidocs/javax/money/MonetaryAmount.html) and I can see that the specification does actually call out that
> two different implementations types with the same currency and numeric value are NOT equal.

**Comment by keilw** [comment]
Thanks for the confirmation, if you believe methods like isEquivalent() may help in a future version of the API, then please feel free to suggest that.
