### ISSUE TITLE
Missing entries in MR1 moneta-core module-info.java

### ISSUE THREAD

**Issue by nemphys** [JavaMoney/jsr354-ri#332]
The moneta-core module's module-info.java lacks the following entries:

provides org.javamoney.moneta.spi.MonetaryConfigProvider with DefaultConfigProvider;
uses org.javamoney.moneta.spi.MonetaryConfigProvider;

which seem to be required after 55e8bfed829486175e4a0d5ff656f4665532209d.

Without the above entries, the following error is produced at runtime: java.util.ServiceConfigurationError: org.javamoney.moneta.spi.MonetaryConfigProvider: module org.javamoney.moneta does not declare `uses`.

**Comment by keilw** [comment]
Strange this did not show in https://github.com/JavaMoney/javamoney-examples/tree/master/console/javamoney-console-java10 which also uses Jigsaw modules, but will retest there. Do you have an example code to reproduce of your own?

**Comment by nemphys** [comment]
Sorry, no example code, but it crashes with the above exception as soon as a simple statement like the following is executed:
CurrencyUnit currency = Monetary.getCurrency("EUR");

**Comment by nemphys** [comment]
Any idea if 1.4.1 will be released soon?
I am asking because this is quite important and 1.4 spent almost 2 years in the oven :-)

**Comment by keilw** [comment]
1.4 is the MR1 of JSR 354, it took a lot more than just fixing a few bugs or improving things, we had to wait for the the Transfer of the Maintenance Lead from Credit Suisse first. As the JSR is now mostly driven by individuals and we all have day jobs or (as in my case or @otaviojava's) even lead multiple JSRs and projects, we have to coordinate and prioritize. Not sure, if you're a JCP member or  would like to join? It seems you're from Greece like @thodorisbais, we welcome further contributors either as EG members or Associate members, if that was the better membership option. 1.4.1 is a service or fix pack, so we'll wait till 1.4 is approved by the JCP EC (otherwise we would also need such version to fix whatever concerns they might have) but it should not take more than a few weeks. We hope to propose a follow-up JSR and both companies and individuals are welcome, if you'd like to participate.
