### ISSUE TITLE
MonetaryConversions.getConversion loosing rate date for exchange rate providers

### ISSUE THREAD

**Issue by l-ray** [JavaMoney/jsr354-ri#374]
Following the example to retrieve conversion rates for a given historic point in time
```
Money
    .of(BigDecimal.TEN, "EUR")
    .with(
      MonetaryConversions.getConversion(
          ConversionQueryBuilder.of()
		.setTermCurrency("USD")
		.set(LocalDate.of(2015, 1, 5))
		.build()
      )
)
```
the LocalDate information is lost within calling `MonetaryConversions.getConversion`  (calling `MonetaryConversions#getMonetaryConversionsSpi().getConversion(conversionQuery)` -> calling `MonetaryConversionsSingletonSpi#getConversion(ConversionQuery conversionQuery)`)

The code fragment in question is

```
    default CurrencyConversion getConversion(ConversionQuery conversionQuery) {
        return this.getExchangeRateProvider(conversionQuery).getCurrencyConversion((CurrencyUnit)Objects.requireNonNull(conversionQuery.getCurrency(), "Terminating Currency is required."));
    }
```

With a custom exchange rate provider, the issue manifests in

```
public class CustomExchangeRateProvider extends AbstractRateProvider {
   ...
       @Override
	public ExchangeRate getExchangeRate(ConversionQuery conversionQuery) {
		CurrencyUnit baseCurrency = conversionQuery.getBaseCurrency();
		CurrencyUnit currency = conversionQuery.getCurrency();
		LocalDate aDate = conversionQuery.get(LocalDate.class); // <- NullPointerException
		return ...;
	}
   ...
}
```

With the OTB exchange rate providers, it seems to work as those use the current LocalDate as fallback. I wrote the following test, that fails accordingly (minimal reproduceable example at [https://github.com/l-ray/javamoney-poc/](https://github.com/l-ray/javamoney-poc/))

```
       @Test
	void selectsFromECBWithGivenDate() {
		MonetaryAmount inEUR = Money.of(BigDecimal.TEN, "EUR");

		CurrencyConversion conv2 = MonetaryConversions.getConversion(ConversionQueryBuilder.of()
				.setProviderName("ECB-HIST")
				.setTermCurrency("USD")
				.set(LocalDate.now())
				.build());

		CurrencyConversion conv1 = MonetaryConversions.getConversion(
				ConversionQueryBuilder.of()
						.setProviderName("ECB-HIST")
						.setTermCurrency("USD")
						.set(LocalDate.of(2008, 1, 1))
						.build()
		);

		assertEquals(inEUR.with(conv1), inEUR.with(conv1));
		assertEquals(inEUR.with(conv2), inEUR.with(conv2));
		assertNotEquals(inEUR.with(conv1), inEUR.with(conv2)); // <- failing step
	}
```
Hope, this is helpful.

**Comment by l-ray** [comment]
Thanks for the super fast response. 

The example basically holds the unit test from above as maven project and github actions so see the failing test.
I opened the issue here as IMO the source is [javax.money.spi.MonetaryConversionsSingletonSpi](https://github.com/JavaMoney/jsr354-api/blob/9f64034e01550dcc593cb3b81ba79103a82c82c8/src/main/java/javax/money/spi/MonetaryConversionsSingletonSpi.java)

This said, feel free .... whatever is the best location in your opinion. Again, thanks for the fast pick-up.

**Comment by keilw** [comment]
Sorry it took a bit before we could look into this, but I analyze this problem as part of anticipating a 1.4.3 release in the near future.

Since there are separate problems accessing the configuration in unit tests, I created an [ECBExample](
https://github.com/JavaMoney/javamoney-examples/blob/master/console/javamoney-console-java8/src/main/java/org/javamoney/examples/console/java8/convert/ECBExample.java) for all 3 variants with "ECB" as the default. It works for "ECB" and "ECB-HIST90", but so far fails for "ECB-HIST", similar to the test case you mentioned above.

There could be an issue with the XML file `eurofxref-hist.xml` retrieved from ECB, but the error is rather fuzzy. I don't think the date is really lost, because it works for `eurofxref-hist-90d.xml` and results in different exchange rates for different dates, as long as it isn't a holiday, but the same day fails for ECBHistoric, although that date is included in the XML.

**Comment by keilw** [comment]
This seems like an encoding issue or problem with illegal characters at least in ECB-HIST:

- https://github.com/opencart/opencart/issues/11453

Have to check that further, also analyzing [exchange](https://github.com/woorea/exchange) which is a Spring Boot API backed by ECB rates.

**Comment by keilw** [comment]
I created a [fork of exchange](https://github.com/JavaMoney/exchange) here. And it works rather convincing althouth the original repo hasn't been touched in over 6 years.
Even adding the full ECB-HIST URL works like a charm in addition to the ECB current and ECB-HIST90 ones. Allowing to use exchange rates in the original timeframe like April 2017. There seems no major delay despite that approach using DOM instead of SAX, but obviously it looks less error-prone for ECB data.

**Comment by keilw** [comment]
This is still a major blocker as the SAX Parser consistently fails for ECB-HIST with:
```
Exception in thread "main" javax.money.MonetaryException: Failed to load currency conversion data: Last Error during data load: Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.javamoney.moneta.convert.ecb@1.4.3-SNAPSHOT/org.javamoney.moneta.convert.ecb.ECBAbstractRateProvider.getExchangeRate(ECBAbstractRateProvider.java:154)
```

**Comment by keilw** [comment]
There has been a major breakthrough. While the cache in moneta-core still uses the error-prone InputStream, which for ECB-HIST becomes a binary chunk instead of an XML file, the retrieval of the exchange rates as such already works by using
`new InputSource(new URL(<rateURl>).openStream()) `instead of an `InputSource` based on the `InputSteeam`.
