### ISSUE TITLE
AWG cash rounding is not supported

### ISSUE THREAD

**Issue by Testsubject1683** [JavaMoney/jsr354-ri#407]
Arubian Florin has 5 cents as the smallest denomination. Currently Moneta has no special handling for cash rounding with AWG.
I already created a PR which should fix it https://github.com/JavaMoney/jsr354-ri/pull/405

**Comment by sschuerz** [comment]
Is there a chance to timely get a release including the change?

**Comment by keilw** [comment]
@sschuerz Could you test it in the 1.4.5-SNAPSHOT build? 
We still have a few issues to solve: https://github.com/JavaMoney/jsr354-ri/milestone/11
Of those only #413 is negotiable, because it mainly affects testing, we could shift it to 1.5 or 1.4.6, the others need to be resolved before we do a new release.

**Comment by keilw** [comment]
Is already merged.
